_base_: '../_base_/isaid.yml'

train_dataset:
  type: Dataset
  dataset_root: data/custom_dataset_size_plz_2
  train_path: data/custom_dataset_size_plz_2/train.txt
  num_classes: 4 #16
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

model:
  type: UPerNet #FCN
  backbone:
    #type: HRNet_W18 #ResNet50
    #type : #STDC2
    #pretrained: #https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz #https://paddle-hapi.bj.bcebos.com/models/resnet50.pdparams
    #pretrained : https://paddle-hapi.bj.bcebos.com/models/resnet50.pdparams
  num_classes: 4 #16
  pretrained: Null
  backbone_indices: [-1]
